name: modulome_sc_qc
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - matplotlib
  - seaborn
  - pydeseq2
  - pandas
  - adjusttext
  - notebook
  - numpy
  - jupyterlab
  - scipy
  - tqdm
  - ipywidgets
  - scikit-learn